### ISSUE TITLE
ES-9 Manual 1.1: Routing Section Typo

### ISSUE THREAD

**Issue by trotttrotttrott** [expertsleepersltd/issues#249]
From [manual 1.1](https://www.expert-sleepers.co.uk/downloads/manuals/es9_user_manual_1.1.pdf):

> ...Outputs 9-16 are straightforward, since they're set to hardware outputs 1-8 i.e. DAW channels **9-61** drive the 3.5mm outputs...

I believe the 61 should be a 16.

**Comment by expertsleepers** [comment]
Thanks.
