### ISSUE TITLE
use first MIDI clock as 'clock time', not start message

### ISSUE THREAD

**Issue by expertsleepers** [expertsleepersltd/issues#287]
https://modwiggler.com/forum/viewtopic.php?p=3574557#p3574557

>I'm syncing the FH-2 (firmware v1.14) to an SND ACME-4 MIDI clock which runs into the FH-2 via PCB expansion header (no USB involved). The ACME is sending straight MIDI clock no shift/shuffle funny business. I have the FH-2 configured to generate a Run/Stop signal and a 16th note clock pulse via the FH-2's clock generators.

>The ACME-4 is apparently unusual in that it sends the MIDI Start command two 16th notes (250ms @ 120bpm) before the first MIDI Clock tick. The FH-2 16th note clock generator goes high on the MIDI Start 250ms before the first MIDI Clock and resumes normal operation on the 2nd MIDI Clock tick. Basically the first downbeat starts on MIDI Start instead of first MIDI Clock which is exacerbated by the ACME's relatively large window of time between those two messages. Shouldn't the FH-2's normal non-transport Clock Type #1 fire on the first MIDI Clock instead of MIDI Start?

**Comment by expertsleepers** [comment]
1.4.1beta

[image.hex.zip](https://github.com/expertsleepersltd/issues/files/6916272/image.hex.zip)

**Comment by SeaweedSound** [comment]
Looks fixed on v1.14.1beta, thank you! Details in modwiggler thread
