### ISSUE TITLE
SysEx messages for looper clear/query as for i2c

### ISSUE THREAD

**Issue by expertsleepers** [expertsleepersltd/issues#396]
https://modwiggler.com/forum/viewtopic.php?p=3676248#p3676248

**Comment by expertsleepers** [comment]
[distingEX_1.11.2beta.hex.zip](https://github.com/expertsleepersltd/issues/files/7854537/distingEX_1.11.2beta.hex.zip)

clear:
F0 00 21 27 5D 60 06 58 F7

get state:
F0 00 21 27 5D 60 06 59 index F7

**Comment by jroo** [comment]
Amazing, thank you. I was able to test "clear" and it worked great. I'll see if I can test "get state" tonight.
