### ISSUE TITLE
USB hub chaining support

### ISSUE THREAD

**Issue by brandond** [expertsleepersltd/issues#565]
I know that only 4 USB devices are supported on the USB-A port, but I grabbed a powered USB hub off Amazon and it happened to be a 7 port device. Unfortunately this is implemented as a 4 port hub chained off another 4 port hub - so only the first three ports can be used, as the FH-2 seems to only support devices connected to the first hub. I couldn't find this limitation (no hub chaining) listed anywhere in the docs. Would it be possible to support hub chaining, even if we have to continue to live with the 4 device limitation?

At the moment I'm working around this by connecting all the devices and the FH-2 to a computer, and running MIDI-OX to repeat all the messages from the devices back to the FH-2, but obviously that doesn't work when I'm not at my desk.

**Comment by brandond** [comment]
I'd label this FH-2 but it appears I'm not allowed to.

**Comment by expertsleepers** [comment]
Not possible, sorry.

**Comment by brandond** [comment]
Fair enough. Could the docs maybe be updated to include this? I would have tried harder to find a 4-port powered device if I'd known of this limitation. All it says right now is 4 devices which I assumed to mean a max of 4 usb-midi devices would be detected, there's no mention of restrictions to the USB topology itself.

**Comment by expertsleepers** [comment]
It says it supports "a hub", not multiple hubs, so it's kind of implicit, but I don't mind spelling it out in more detail. I'll do that next release.

**Comment by brandond** [comment]
Yeah, it just sucks when what is sold as and physically presented as a single hub is actually multiple chained hub chipsets. I suspect this is a pretty common configuration, since most USB implementations don't care about the topology, and 4-port hub chips are cheap. I had to pull up UsbTreeView just to figure out what was going on, and then confirmed the issue by trying to plug separate physical hubs in to each other with the MIDI devices at the end.
