### ISSUE TITLE
If MIDI Rx for dual L and dual R are both set to the same value, I3/J2/J6 will just break when you press a midi note

### ISSUE THREAD

**Issue by expertsleepers** [expertsleepersltd/issues#57]

**Comment by expertsleepers** [comment]
Believed fixed in 1.3beta8.

**Comment by Jademalo** [comment]
Good news, that doesn't crash and seems to functionally work correctly. However, there's a sort of constant static clicking over all of the audio when in J6 mode. SD multisample was also weirdly glitchy and noisy too, almost like when you've got too low of an asio buffer set in ableton or something. Not exactly sure how to describe it.

Reverting back to 1.2 stopped the crackling (mostly, there were still one or two clicks for some reason).
