### ISSUE TITLE
I-7 - Using I-7 on both sides in Dual Mode breaks audio output until a restart

### ISSUE THREAD

**Issue by Jademalo** [expertsleepersltd/issues#59]
On the Disting EX in Dual mode, one I-7 seems to be fine, but when using one on each side the audio glitches out and then stops entirely. Turning Z also doesn't update which WAV file is being played on the display, and switching to different folders doesn't fix it.

The only fix seems to be a restart, but only so long as I-7 isn't loaded on startup. If a single I-7 is loaded on startup then the audio is glitchy, and obviously if both sides load I-7 then the audio output stops working.

My SD card does ~3MB/s for all three metrics, and considering my samples are under 100kb each I don't believe that's the issue.

(And yes I know SD 6 Triggers superceeds the use of this mostly, though it still seems worth mentioning.)

**Comment by expertsleepers** [comment]
Could you please try
https://github.com/expertsleepersltd/issues/blob/master/beta%20releases/distingEX_1.3beta8.hex.zip
?

**Comment by Jademalo** [comment]
Apologies, I totally and utterly forgot to test the beta yesterday. 
From the quick tests that I've done, it seems to be working in this version.
