### ISSUE TITLE
Preset names for Dual Mode presets don't load correctly

### ISSUE THREAD

**Issue by Jademalo** [expertsleepersltd/issues#60]
I have a dual mode preset called `Drum Machine`. I set this name and saved it, and on the preset list this is what it shows.

When loading a single mode preset, the name correctly loads into the Preset Name option, and if you then save it to the SD card it saves it correctly using that name.
When loading a dual mode preset, it seems to fail loading the name. The Preset Name option shows the name of the preset that was loaded before it (such as Init), instead of the name of the loaded preset. If it's loaded and saved to the SD card, the same thing occurs and it saves it under the name of the previously loaded preset.

**Comment by expertsleepers** [comment]
Fixed.
