### ISSUE TITLE
Z-Function not saved correctly in Dual Mode

### ISSUE THREAD

**Issue by Jademalo** [expertsleepersltd/issues#61]
This one is a bit weird, because it's fairly inconsistent and I can't reproduce it reliably.

On the Disting EX, I have default profile set to 1 and Auto Save Change Alg enabled so it behaves like the Disting mk4 where when you switch to an algorithm, it saves a preset.

I loaded I-1, and the Z-Function was set to 0 by default. I then restarted the module, and Z-function had changed to 3. This makes no sense since I hadn't done it manually, but also the profile that was loaded was the one that was autosaved when I selected I-1 originally.

**Comment by expertsleepers** [comment]
Fixed.
