### ISSUE TITLE
I-1 - retriggerOnSampleChange=0 breaks switching between wav files

### ISSUE THREAD

**Issue by Jademalo** [expertsleepersltd/issues#62]
This is an extremely weird one, especially considering it happens on both the EX and the mk4.

I have a folder full of 808 samples, which is item 0 in playlist.txt. This works fine, and I can switch between every sample in the folder using the Z knob.
I have a folder with Mutable Instruments firmware wavs, which is item 1 in playlist.txt. For whatever reason, this only lets me select a single .wav file from the folder. I can't change it with the Z knob, and no matter how I have playlist.txt set it will only show one at a time.
I have a folder with a multisampled instrument from the autosampler, which is item 2 in playlist.txt. This behaves the same as above, and I can only select a single .wav file from the folder.

After doing some more testing, the thing that the two other folders have in common is `-retriggerOnSampleChange=0`. Having this set seems to break switching wav file with the Z knob.
Removing this line seems to make it work again, though due to the nature of the Mutable Firmware files I want this to be designated.

My only assumption is that I-1 changes the default of that to 0, and then re-establishing it in the playlist.txt breaks something, but I'm obviously not sure.

Here are the playlist.txt files in case you need them specifically

Mutable Firmware - 
```
disting playlist v1
-loop=0
-gap=0
-fadeIn=0
-fadeOut=0
-retriggerOnSampleChange=0
-fixedPitch=1
-playToCompletion=1
-useStartOnSampleChange=1
```
[playlist.txt](https://github.com/expertsleepersltd/issues/files/4809209/playlist.txt)

Multisampled Instrument - 
```
disting playlist v1
-loop=0
-retriggerOnSampleChange=0
050_D3.wav
-natural=50
056_G#3.wav
-switch=53
-natural=56
062_D4.wav
-switch=59
-natural=62
068_G#4.wav
-switch=65
-natural=68
074_D5.wav
-switch=71
-natural=74
080_G#5.wav
-switch=77
-natural=80
086_D6.wav
-switch=83
-natural=86
092_G#6.wav
-switch=89
-natural=92
098_D7.wav
-switch=95
-natural=98
0104_G#7.wav
-switch=101
-natural=104
```
[playlist.txt](https://github.com/expertsleepersltd/issues/files/4809216/playlist.txt)

**Comment by expertsleepers** [comment]
That's what -retriggerOnSampleChange=0 means. It means don't change sample unless the trigger input (X on I-1) gets a trigger.

**Comment by Jademalo** [comment]
Aaah, I see, my mistake. 
I was under the impression that it meant "Automatically trigger the sample when it is switched to". As in, retrigger the sound on the sample change.
