### ISSUE TITLE
Poly FM missing i2c messages

### ISSUE THREAD

**Issue by expertsleepers** [expertsleepersltd/issues#660]
https://llllllll.co/t/expert-sleepers-disting-ex/31596/382?u=expertsleepers

**Comment by expertsleepers** [comment]
[distingEX_1.21.1beta.hex.zip](https://github.com/expertsleepersltd/issues/files/11816644/distingEX_1.21.1beta.hex.zip)

**Comment by justmat** [comment]
only had a quick test, but so far so good! i let a sequence play for a couple of minutes with no missing/dropped notes. thanks for the quick fix!
