### ISSUE TITLE
add new i2c note commands with channel

### ISSUE THREAD

**Issue by expertsleepers** [expertsleepersltd/issues#661]
https://llllllll.co/t/teletype-disting-ex-integration/33929/183?u=expertsleepers

```
set voice pitch for note id with channel
<address> 0x67 <channel> <note id> <pitch MSB> <pitch LSB>

note on for specified note id with channel
<address> 0x68 <channel> <note id> <velocity MSB> <velocity LSB>

note off for specified note id with channel
<address> 0x69 <channel> <note id>

the existing note commands 0x54-0x56 could default to channel 1 and we could add another command for changing the channel:

set channel for note commands
<address> 0x6A <channel>
```

```
we have a dedicated command for “all notes off” but i agree that reserving 0 might be useful for some future purpose. so, 1-based in teletype and it will be send unmodified.
```

**Comment by expertsleepers** [comment]
As above but one higher (0x68-0x6B) since 0x67 was already used.

[distingEX_1.21.2beta.hex.zip](https://github.com/expertsleepersltd/issues/files/11866250/distingEX_1.21.2beta.hex.zip)

**Comment by scanner-darkly** [comment]
the new commands seem to work but observing a couple of issues:

- looks like the new commands are only supported for the poly FM algo - is it possible to make them work for other algos that can be used with notes? this way we can use the same teletype ops for all algos (other algos can just ignore the channel parameter).

- when sending notes to multiple channels (i tried 2) at some point it starts dropping notes, sometimes several in a row. once it's in this condition, even if i leave one channel only, it still drops some notes. sending it "all notes off" `0x57` command sometimes helps with the issue but not always.

- noticed that "all notes off" can cause clicks. also repeatedly sending it after playing some notes seems to cause the note display on the bottom to lose some pixels, like it's redrawing it but not fully.

to confirm, this is what gets sent when i send notes:

note off for specified note id with channel
`<address> 0x6A <channel> <note id>`

set voice pitch for note id with channel
`<address> 0x68 <channel> <note id> <pitch MSB> <pitch LSB>`

note on for specified note id with channel
`<address> 0x69 <channel> <note id> <velocity MSB> <velocity LSB>`

i've confirmed using the i2c monitor the disting ex receives the above correctly.

**Comment by scanner-darkly** [comment]
forgot to add, i've updated the spec with the latest: https://github.com/scanner-darkly/teletype/wiki/DISTING-EX-I2C-SPECIFICATION

**Comment by expertsleepers** [comment]
This version should support the new commands for all algorithms (that previously supported the other form), ignoring the channel:

[distingEX_1.21.2beta.hex.zip](https://github.com/expertsleepersltd/issues/files/12079082/distingEX_1.21.2beta.hex.zip)

**Comment by scanner-darkly** [comment]
i'm able to use the new commands with other algos.

found a couple of new issues:
- tuning seems to be off. i checked and under scala i have "none". i haven't checked if it's just the new commands. seems to be the same with all note playing algos.
- when poly FM algo is selected, if i query the current algorithm it returns 255 while "No FMSYS folder found" message is displayed. once i click to make it go away, it returns the correct algorithm.

**Comment by scanner-darkly** [comment]
i've confirmed that the pitch is definitely off when using the new commands. it sounds like it's scaled wrong and like there is some rounding that results in some adjacent notes having the same pitch. this is the case for all note generating algos. the old commands work correctly.

one more issue - if i select the poly FM algo, and it shows the "No FMSYS folder found" message, if i then change the algorithm via i2c, it does change it but the message is still displayed until i press something.

**Comment by expertsleepers** [comment]
Struggling to see how the pitch can be wrong. Both forms of the message call the same code, e.g. 
```
            case kI2C_note_pitch:
            {
                // (1<<14) == 10V
                int pitchCV = ( ( (int)msg[2] << 24 ) | ( (int)msg[3] << 16 ) ) >> 16;
                s_sdMulti_i2c_note_pitch( note, pitchCV );
            }
```
```
            case kI2C_channel_note_pitch:
            {
                int pitchCV = ( ( (int)msg[3] << 24 ) | ( (int)msg[4] << 16 ) ) >> 16;
                s_sdMulti_i2c_note_pitch( note, pitchCV );
            }
```

**Comment by scanner-darkly** [comment]
here is a video demonstrating the issue (using poly wavetable algo here): https://www.dropbox.com/s/wf17j0scil1ydwn/2023-07-20_10-47-43.mp4?dl=0

i'm using the i2c monitor to confirm i'm sending the correct data. i start by sending a bunch of "all notes off" 0x57 messages, then play a note using the old commands, send a bunch of "all notes off" again, then send the same note using the new commands. 

the pitch value is 0x89, the velocity value is 0x2000.

the old commands (the following values are all hex, omitting 0x for clarity):

note off for specified note id `<address> 0x56 <note id>`
56 31 
set voice pitch for note id `<address> 0x54 <note id> <pitch MSB> <pitch LSB>`
54 31 00 89
note on for specified note id `<address> 0x55 <note id> <velocity MSB> <velocity LSB>`
55 31 20 00

the new commands, exactly the same except the command values and the channel byte being included:

note off for specified note id with channel `<address> 0x6A <channel> <note id>`
6A 01 31
set voice pitch for note id with channel `<address> 0x68 <channel> <note id> <pitch MSB> <pitch LSB>`
68 01 31 00 89
note on for specified note id with channel `<address> 0x69 <channel> <note id> <velocity MSB> <velocity LSB>`
69 01 31 20 00

**Comment by expertsleepers** [comment]
Sorry, stupid bug.

[distingEX_1.22beta.hex.zip](https://github.com/expertsleepersltd/issues/files/12280571/distingEX_1.22beta.hex.zip)

**Comment by scanner-darkly** [comment]
this version seems to work! (tried it with sd multisample and poly fm)

**Comment by scanner-darkly** [comment]
forgot to add, the new ops will be added to teletype 5.0 which is currently in beta testing (i will post a new beta with the new ops included in a couple of days)
