### ISSUE TITLE
revise algorithm-specific I2C messages

### ISSUE THREAD

**Issue by expertsleepers** [expertsleepersltd/issues#701]
https://llllllll.co/t/teletype-disting-ex-integration/33929/214?u=expertsleepers

Looper
7 target loop
55 record
56 play
57 reverse
58 octave down

**Comment by expertsleepers** [comment]
[distingEX_1.23.2beta.hex.zip](https://github.com/expertsleepersltd/issues/files/12844256/distingEX_1.23.2beta.hex.zip)

In looper, you can now use

`0x6C <legacy parameter number as above> <value MSB> <value LSB>
`

Value is the actual parameter value, as for message 0x46.

**Comment by scanner-darkly** [comment]
so the new format so far only applies to the above looper commands? would it be possible to extend it to all algos/parameters? otherwise we'd still need to make changes to the teletype firmware if any other parameter indexes get changed.

**Comment by expertsleepers** [comment]
As I understood it, it was only the looper parameter numbers that were hardwired into the Teletype.

In any other case, the parameter numbers would be part of the user's script, and so could be changed by them if needed.

**Comment by scanner-darkly** [comment]
everything appears to work properly! i've posted a new teletype beta here: https://llllllll.co/t/teletype-5-0-0-beta-testing/62210

**Comment by expertsleepers** [comment]
Thanks.
